### ISSUE TITLE
Unable to get it working 

### ISSUE THREAD

**Issue by arsaboo** [jjleng/sensei#2]
I tried to get this working but failed. I have Ollama installed as a regular app on my Mac. I updated the docker to add extra_hosts (also had to change some ports):
```yaml

version: '3.9'

services:
  frontend:
    volumes:
      - ./frontend/app:/app/app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3015:3000
    depends_on:
      - backend
  backend:
    volumes:
      - ./backend:/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8004:8000
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: redis:alpine
  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./ops/searxng:/etc/searxng
    ports:
      - 8081:8080
    environment:
      - SEARXNG_URL=http://localhost:8081/
      - SEARXNG_SECRET=SQRXTEUTa%SMuWDiF_kyH&,:EqBpTV
      - SEARXNG_REDIS_URL=redis://redis:6379/0
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    depends_on:
      - redis
```

I see the UI, but get no search results. I see the following in the browser console:

![image](https://github.com/jjleng/sensei/assets/18319734/e39f3c66-7b5c-4a4d-9a96-f17fe0df1810)

BTW...strongly recommend that you consolidate all the env variables in one file in the root.

**Comment by jjleng** [comment]
my bad. Forgot to copy my local `.env.development` to the `.env.development.example`. .env.development.example now looks like

```
LOGURU_LEVEL=DEBUG
SEARXNG_URL="http://searxng:8080"
REDIS_HOST="redis"

# Small model
SM_MODLE_URL="http://host.docker.internal:11434/v1/" # host.docker.internal rather than localhost
SM_MODEL="llama3:instruct"
SM_MODEL_API_KEY="whatever"

# Medium model
MD_MODLE_URL="http://host.docker.internal:11434/v1/" # same
MD_MODEL="command-r"
MD_MODEL_API_KEY="whatever"
```

**Comment by arsaboo** [comment]
Still not working for me:

![image](https://github.com/jjleng/sensei/assets/18319734/5e36ff5d-1f55-45b4-aba1-1c74894ed511)

```yaml

LOGURU_LEVEL=DEBUG
SEARXNG_URL="http://searxng:8081"
REDIS_HOST="redis"

# Small model
SM_MODLE_URL="http://host.docker.internal:11434"
SM_MODEL="llama3:8b-instruct-q5_0"
SM_MODEL_API_KEY="whatever"

# Medium model
MD_MODLE_URL="http://host.docker.internal:11434"
MD_MODEL="llama3:8b-instruct-q5_0"
MD_MODEL_API_KEY="whatever"
```

Docker compose:
```yaml
services:
  frontend:
    volumes:
      - ./frontend/app:/app/app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3015:3000
    depends_on:
      - backend
  backend:
    volumes:
      - ./backend:/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8004:8000
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: redis:alpine
  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./ops/searxng:/etc/searxng
    ports:
      - 8081:8080
    environment:
      - SEARXNG_URL=http://localhost:8081/
      - SEARXNG_SECRET=SQRXTEUTa%SMuWDiF_kyH&,:EqBpTV
      - SEARXNG_REDIS_URL=redis://redis:6379/0
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    depends_on:
      - redis
```

**Comment by jjleng** [comment]
I suspect that you had a CORS issue. https://github.com/jjleng/sensei/blob/7db5252d5172730b1455639aa2d6cb841fedaca7/backend/sensei_search/server.py#L12.

Because the server assumes the client runs on port 3000. Since you have changed port, the browser blocked the connection because the request violated CORS policy. I will try to make the CORS policy work with any ports for dev environment.

Thanks for reporting!

**Comment by jjleng** [comment]
https://github.com/jjleng/sensei/pull/11 should have disabled CORS for the docker compose.

**Comment by arsaboo** [comment]
Still not working:

![image](https://github.com/jjleng/sensei/assets/18319734/c2e60cbb-c021-4fe4-bf81-7ecc23116d50)

Do I need to change the env in frontend? This is what I have right now:
```yaml
NEXT_PUBLIC_SOCKET_HOST=http://localhost:8000
```

**Comment by jjleng** [comment]
ah yes, it should be 8004. because you are mapping the docker port to be 8004 on your host

```
  backend:
    volumes:
      - ./backend:/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8004:8000
```

**Comment by arsaboo** [comment]
More reasons....for all config variables to be in one place. 

Anyways, it is still not working for me:

![image](https://github.com/jjleng/sensei/assets/18319734/9e5ecc9a-a6cf-4b04-8f8c-2eb80e20bf09)

Here's docker-compose:
```yaml
services:
  frontend:
    volumes:
      - ./frontend/app:/app/app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3015:3000
    depends_on:
      - backend
  backend:
    volumes:
      - ./backend:/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8004:8000
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: redis:alpine
  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./ops/searxng:/etc/searxng
    ports:
      - 8081:8080
    environment:
      - SEARXNG_URL=http://localhost:8081/
      - SEARXNG_SECRET=SQRXTEUTa%SMuWDiF_kyH&,:EqBpTV
      - SEARXNG_REDIS_URL=redis://redis:6379/0
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    depends_on:
      - redis
```

Frontend env:
```yaml
NEXT_PUBLIC_SOCKET_HOST=http://localhost:8004
```

Backend env:
```yaml
LOGURU_LEVEL=DEBUG
SEARXNG_URL="http://searxng:8081"
REDIS_HOST="redis"

# Small model
SM_MODLE_URL="http://host.docker.internal:11434"
SM_MODEL="llama3:8b-instruct-q5_0"
SM_MODEL_API_KEY="whatever"

# Medium model
MD_MODLE_URL="http://host.docker.internal:11434"
MD_MODEL="llama3:8b-instruct-q5_0"
MD_MODEL_API_KEY="whatever"
```

**Comment by jjleng** [comment]
Sorry for your frustration. I updated my local env to be the same as yours. Here are the changes you need to make


docker compose

```
services:
  frontend:
    volumes:
      - ./frontend/app:/app/app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3015:3000
    depends_on:
      - backend
  backend:
    volumes:
      - ./backend:/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8004:8000
    depends_on:
      - redis
  redis:
    image: redis:alpine
  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./ops/searxng:/etc/searxng
    ports:
      - 8081:8080
    environment:
      - SEARXNG_URL=http://localhost:8081/
      - SEARXNG_SECRET=SQRXTEUTa%SMuWDiF_kyH&,:EqBpTV
      - SEARXNG_REDIS_URL=redis://redis:6379/0
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    depends_on:
      - redis
```

I removed from your original docker compose

```
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

Backend env:

```
LOGURU_LEVEL=DEBUG
SEARXNG_URL="http://searxng:8080" # Use 8080 not 8081 since we updated the above docker-compose
REDIS_HOST="redis"

# Small model
SM_MODLE_URL="http://host.docker.internal:11434/v1" # You need to add /v1. This is Ollama's OpenAI API endpoint
SM_MODEL="llama3:instruct"
SM_MODEL_API_KEY="whatever"

# Medium model
MD_MODLE_URL="http://host.docker.internal:11434/v1" # You need to add /v1. This is Ollama's OpenAI API endpoint
MD_MODEL="llama3:instruct"
MD_MODEL_API_KEY="whatever"
```
See my comments, you need to add /v1 to the URLs.

Frontend dev:

`NEXT_PUBLIC_SOCKET_HOST=http://localhost:8004`

Now go to browser http://localhost:3015/. However, my prompt is too long for llama3 8b to handle. You can play with the prompts. Happy coding :)

![Screenshot 2024-06-21 at 12 02 17 PM](https://github.com/jjleng/sensei/assets/962285/9e6da7a0-b5b6-4076-87de-e39562f25db2)
